theme: jekyll-theme-minimal
title: "Watson-Phillips’ GT CS 3312"
description: This course is the second part of a 2 semester course series that is taught in tandum with an LMC course each semester (LMC 3432/3431). In this series students spend 2 semsters working with a real world client to document and build a software product in a project group. This site focuses on the CS side of the course series and provides resource, examples and lesson plans.
logo: logo.jpg
show_downloads: false
